spring:

  datasource:
  
    url: jdbc:mysql://localhost:3306/userdata
    username: root 
    password: root1234
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true
    
    
  security:
    oauth2:
      client:
        registration:
         google:
          clientId: 182412537841-g1p01dsao2039359np881rco97t960gn.apps.googleusercontent.com
          clientSecret: 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
          scope:
           - email
           - profile
   